services:
    Enhavo\Bundle\DashboardBundle\Menu\DashboardMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\DashboardBundle\Dashboard\DashboardManager:
        arguments:
            - '@Enhavo\Component\Type\FactoryInterface[DashboardWidget]'
            - '@security.authorization_checker'
            - '%enhavo_dashboard.widgets%'

    Enhavo\Bundle\DashboardBundle\Dashboard\Type\NumberDashboardWidgetType:
        arguments:
            - '@translator'
            - '@Enhavo\Bundle\ResourceBundle\Resource\ResourceManager'
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: enhavo_dashboard.widget }

    Enhavo\Bundle\DashboardBundle\Dashboard\Type\BaseDashboardWidgetType:
        tags:
            - { name: enhavo_dashboard.widget }

    Enhavo\Bundle\DashboardBundle\Endpoint\DashboardEndpointType:
        arguments:
            - '@Enhavo\Bundle\DashboardBundle\Dashboard\DashboardManager'
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }