enhavo_dashboard_admin_index:
    path: /dashboard
    defaults:
        _expose: admin
        _vue:
            component: dashboard-index
            groups: admin
        _endpoint:
            type: admin
